---

- name: Setup Debian 11 host running k3s
  hosts: linode
  become: true
  tasks:
    - name: "[dynamic motd] backup /etc/update-motd.d on host"
      copy:
        src: /etc/update-motd.d
        dest: /etc/update-motd.d.backup-{{ansible_date_time.date}}
        remote_src: yes
    - name: "[dynamic motd] copy update-motd.d to host"
      copy:
        src: ./update-motd.d/
        dest: /etc/update-motd.d/
        