#!/bin/bash

. /etc/update-motd.d/quiet
. /etc/update-motd.d/colors

n=$(apt-get -qq --just-print dist-upgrade | cut -f 2 -d " " | sort -u | wc -l)
if [[ $n -gt 0 ]]; then
    printf $CYAN # $RED
    printf "  You have %s packages waiting for upgrades." "$n"
    printf $NONE"\n\n"
fi
