---
services:
  postgres:
    container_name: postgres
    mem_limit: 512M
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=IlikePizza!
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres-user", "-d", "IlikePizza!"]
      interval: 10s
      timeout: 10s
      retries: 5
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=blah@example.org
      - PGADMIN_DEFAULT_PASSWORD=beepboop
      - PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "wget", "-0", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  postgres:
    driver: local
  pgadmin4:
    driver: local